"""Add avatar_data and avatar_mime_type to users

Revision ID: 1b63e9d5b564
Revises: b2c3d4e5f6g7
Create Date: 2026-01-14 04:05:48.236212+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1b63e9d5b564"
down_revision: str | Sequence[str] | None = "b2c3d4e5f6g7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_provisioning_jobs_id"), table_name="provisioning_jobs")
    op.drop_table("provisioning_jobs")
    op.add_column("users", sa.Column("avatar_data", sa.LargeBinary(), nullable=True))
    op.add_column(
        "users", sa.Column("avatar_mime_type", sa.String(length=50), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "avatar_mime_type")
    op.drop_column("users", "avatar_data")
    op.create_table(
        "provisioning_jobs",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "playbook_name", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "PENDING", "RUNNING", "COMPLETED", "FAILED", name="jobstatus"
            ),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "started_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "completed_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("log_output", sa.TEXT(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name=op.f("provisioning_jobs_device_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("provisioning_jobs_pkey")),
    )
    op.create_index(
        op.f("ix_provisioning_jobs_id"), "provisioning_jobs", ["id"], unique=False
    )
    # ### end Alembic commands ###
