"""Add theme preferences to users

Revision ID: 113473d262e7
Revises: 1b63e9d5b564
Create Date: 2026-01-14 17:00:52.033951+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '113473d262e7'
down_revision: Union[str, Sequence[str], None] = '1b63e9d5b564'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('theme_preference', sa.String(length=50), nullable=False, server_default='dark'))
    op.add_column('users', sa.Column('page_accents', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'page_accents')
    op.drop_column('users', 'theme_preference')
    # ### end Alembic commands ###
